### ISSUE TITLE
集成到"nuxt": "^3.0.0-rc.12" 报错

### ISSUE THREAD

**Issue by zhang20084** [koha-dev/nuxt-element-plus-module#6]
ElementPlusError: [IdInjection] Looks like you are using server rendering, you must provide a id provider to ensure the hydration process to be succeed
usage: app.provide(ID_INJECTION_KEY, {
  prefix: number,
  current: number,
})

**Comment by zhang20084** [comment]
在app.vue 加入
`<script setup>
import { ID_INJECTION_KEY } from 'element-plus'
provide(ID_INJECTION_KEY, {
  prefix: 100,
  current: 0,
})
</script>`

**Comment by HigherOrderLogic** [comment]
Firstly, sorry that I don't speak Chinese. And from the error, a solution I can think of is creating a plugin yourself:
```ts
// ~/plugins/element.ts
import { ID_INJECTION_KEY } from "element-plus";

export default defineNuxtPlugin(({ vueApp }) => {
  vueApp.provide(ID_INJECTION_KEY, {
    prefix: 0, // a random number
    current: 0, // also a random number
  });
});
```
This solution works for me.

**Comment by zhang20084** [comment]
hi, 
When the page is refreshed, the following error prompt will appear
![WX20221026-095000](https://user-images.githubusercontent.com/1556397/197915909-4f66982e-7abb-45c2-8961-adfc1578705e.png)
